baseURL = "https://example.com/"
languageCode = "en-us"
title = "West Antique Gallery"
theme = "gallery"

# Enable Hugo's built-in syntax highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"

[params]
  # The title of your site that will be shown in the header
  title = "West Antique Gallery"
  
  # A short description of your site that will be shown in the header
  subtitle = "Showcasing Antiques, Beauty, Fashion and Nature"


  # The path to your favicon
  favicon = "favicon.ico"
  
  # Footer text
  footer = "© 2024 West Antique Gallery"
  
  # Default theme (light or dark)
  defaultTheme = "dark"
  
  # Enable showing related posts
  showRelatedPosts = true
  
  [params.socialIcons]
    # Add your social media links here
    github = "https://github.com/yourusername"
    instagram = "https://www.instagram.com/yourusername"
    # email = "mailto:your.email@example.com"
    taobao = "https://github.com/yourusername"
    Wechat = "https://github.com/yourusername"


[taxonomies]
  category = "categories"
  tag = "tags"

# Related content configuration
[related]
  includeNewer = true
  threshold = 10
  toLower = false
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'categories'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'tags'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 50

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true
